feat: Добавить классы репозитории, сервисы, контроллеры
moratti72r/ShareIt pull request #2
Opened 2023-06-17 10:17 UTC by moratti72r

2023-06-18 09:08 UTC, Donald522 requested changes
Привет!

Написал несколько замечаний небольших. А так все хорошо.

2023-06-18 09:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/item/ItemController.java
> +    public Item create(@RequestHeader("X-Sharer-User-Id") long idUser, @RequestBody @Valid ItemDto itemDto) {
Возвращать надо тоже dto класс

2023-06-18 09:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/item/model/Item.java
> +    @JsonIgnore
На модельных классах в идеале не должно быть этих аннотаций (бывают исключения, если например в колонке в базе храним json)
Здесь нужно убрать, тк в контроллерах надо использовать dto

2023-06-18 09:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/item/repository/ItemRepositoryImpl.java
> +    public Item updateItem(long idUser, long idItem, ItemDto itemDto) {
конвертацию из dto в модельный класс стоит сделать в классе сервисе

2023-06-18 09:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/item/service/ItemServiceImpl.java
> +        log.info("Продукт c id={} успешно изменен Пользователем с id={}", idItem, idUser);
Пишем об успешном изменении до реального изменения
Это может создать проблемы при расследовании инцидентов

2023-06-18 09:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
Почему не импортом?

2023-06-18 09:08 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public List<User> findAll() {
Тут тоже dto надо возвращать

2023-06-18 10:26 UTC, moratti72r commented on src/main/java/ru/practicum/shareit/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
При импорте высвечивает ошибку с названием класса ExceptionHandler. При переименовании класса не проходят тесты на GitHub - выводит ошибку /home/runner/work/ShareIt/ShareIt/src/main/java/ru/practicum/shareit/exception/ShareitExceptionHandler.java:[12,8] class ExceptionHandler is public, should be declared in a file named ExceptionHandler.java

2023-06-19 20:25 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
При переименовании класса надо переименовывать файл тоже

2023-06-19 20:26 UTC, Donald522 approved these changes

2023-06-20 16:30 UTC, merged