feat: добавить классы для работы с БД
moratti72r/ShareIt pull request #3
Opened 2023-06-27 14:20 UTC by moratti72r

2023-06-28 21:49 UTC, db-exp requested changes

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/ApproveStatus.java
> +            if (approveStatus.name().equals(parameter)) {
для верности я бы предложил использовать либо toUpperCase у parameter, либо equalsIgnoreCase

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/item/model/Item.java
> +//    private ItemRequest request;
давай удалим

2023-06-28 21:49 UTC, db-exp commented on src/main/resources/schema.sql
проверь, пожалуйста, в схеме id с integer, а в модели с long, нужно привести к одному виду

2023-06-28 21:49 UTC, db-exp commented on src/main/resources/schema.sql
у varchar не хватает размерности

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
>      public static User fromUserDto(User user, UserDto userDto) {
как мне кажется, лучше создавать User внутри, а не передавать снаружи и менять тут

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/User.java
>  public class User {
на String поля еще можно lenght добавить в Column

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public static Booking fromBookingDto(Booking booking, BookingDto bookingDto) {
как и с User - лучше создавать Booking внутри

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private long bookerId;
по идее тоже не пустой

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            userRepository.deleteById(id);
удалять можно не проверяя, только если того не требует postman тест

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
тут, мне кажется, можно не проверять, а если в запрос уйдет не существующий id - вернется просто пустой список. Только если тесты того не требуют

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new InternalServerException(format("ID {0} NOT EXIST", userId));
Да и NotFound тут подходит тогда лучше

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (status == null) throw new InternalServerException(format("Unknown state: {0}", parameter));
тут лучше либо пустой список вернуть, либо статус проверить на уровне контроллера (можно сделать кастомный валидатор параметра https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new InternalServerException(format("ID {0} NOT EXIST", userId));
NotFound подходит лучше

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (status == null) throw new InternalServerException(format("Unknown state: {0}", parameter));
NotFound подходит лучше

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
тут, мне кажется, можно не проверять, а если в запрос уйдет не существующий id - вернется просто пустой список. Только если тесты того не требуют

2023-06-28 21:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (status == null) throw new InternalServerException(format("Unknown state: {0}", parameter));
@[db-exp](https://github.com/db-exp) db-exp Pending

тут лучше либо пустой список вернуть, либо статус проверить на уровне контроллера (можно сделать кастомный валидатор параметра https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4
@db-exp

2023-06-30 12:29 UTC, moratti72r commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private long bookerId;
Если здесь проставлю @NotNull то не пройдет валидацию при передачи в сущности в контроллер

2023-06-30 12:31 UTC, moratti72r commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
>      public static User fromUserDto(User user, UserDto userDto) {
для частичного обновления объекта не могу найти более лучшего решения. Если можешь подскажи пожалуйста

2023-06-30 14:35 UTC, moratti72r commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
Тесты требуют выбросить исключение

2023-06-30 14:36 UTC, moratti72r commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
тесты требуют выбросить исключение

2023-06-30 14:40 UTC, moratti72r commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (status == null) throw new InternalServerException(format("Unknown state: {0}", parameter));
Тесты требуют выбросить исключение и в ответе вернуть определенное сообщение

2023-06-30 14:42 UTC, moratti72r commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (status == null) throw new InternalServerException(format("Unknown state: {0}", parameter));
Тесты требуют выбросить исключение и в ответе вернуть код 500 и определенное сообщение

2023-06-30 16:33 UTC, closed without merging

2023-06-30 16:34 UTC, moratti72r commented
ууу

2023-07-01 10:34 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
>      public static User fromUserDto(User user, UserDto userDto) {
Это совет по улучшению кода.
fromUserDto вызывается для добавления и обновления.
1) для добавления new User лучше сделать внутри
2) а обновление - 
     можно сделать почти как у тебя, но назвать метод patchUser и перенести его в UserService. Внутри метода достанется user из базы и к нему будут применены обновления из UserDto.
Так ты сделашь код более предсказуемым и понятным. Лучше стремится к метод=одна функция, а сейчас fromUserDto и обновляет по тихому и нового пользователя заполняет.

2023-07-01 10:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (status == null) throw new InternalServerException(format("Unknown state: {0}", parameter));
Спасибо за пояснения по postman'у. Не то, чтобы я был согласен с такой ошибкой как в тестах, но варианта ни у тебя, ни у меня нет - для сдачи работы остается как ты сделал.

2023-07-01 10:41 UTC, db-exp reviewed
Спасибо за доработки, на комментарии ответил