add requests
moratti72r/ShareIt pull request #5
Opened 2023-07-24 20:33 UTC by moratti72r

2023-07-25 20:03 UTC, Donald522 requested changes
Привет!

Написал замечания.

2023-07-25 20:03 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        log.info("Получен POST запрос /requests");
userId как минимум надо добавить в лог
Логировать просто факт запроса особого смысла нет

2023-07-25 20:03 UTC, Donald522 commented on src/main/resources/schema.sql
> +    requestor_id BIGINT REFERENCES users_items (id),
На это поле нужен индекс

2023-07-25 20:03 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        itemRequest.setRequestor(userRepository.findById(idUser).get());
Я бы лучше передал в маппер объект user.
Иначе логика построения IterRequest размазывается

2023-07-26 17:38 UTC, Donald522 approved these changes
Привет!

Индекс, кажется, не на ту колонку добавил. Это не критично в данной работе, скорее написал для понимания того, что в реальной жизни это нужно.

2023-07-26 17:38 UTC, Donald522 commented on src/main/resources/schema.sql
> +CREATE INDEX description_index ON requests (description);
Я имел ввиду индекс на requestor_id )
Я не вижу запросов в эту таблицу по полю description

Поправь к след итерации

2023-07-26 17:42 UTC, moratti72r commented on src/main/resources/schema.sql
> +CREATE INDEX description_index ON requests (description);
Хорошо

2023-07-26 17:45 UTC, merged